---
AllCops:
  Exclude:
    - bin/**/*
  DisabledByDefault: true
  TargetRubyVersion: 2.5

Layout/AccessModifierIndentation:
  EnforcedStyle: indent
Layout/BlockAlignment:
  EnforcedStyleAlignWith: either
Layout/DefEndAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/DotPosition:
  EnforcedStyle: leading
Layout/EmptyComment:
  Enabled: true
Layout/EmptyLineBetweenDefs:
  Enabled: true
  NumberOfEmptyLines: 1
Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines
Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword
Layout/ExtraSpacing:
  AllowForAlignment: true
Layout/IndentationConsistency:
  EnforcedStyle: normal
Layout/IndentationWidth:
  Width: 2
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_no_space
Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
Layout/SpaceAroundOperators:
  Enabled: true
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideReferenceBrackets:
  EnforcedStyle: no_space
Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space
Layout/Tab:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true

Naming/VariableName:
  EnforcedStyle: snake_case

Style/BlockDelimiters:
  EnforcedStyle: line_count_based
Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces
Style/EmptyElse:
  EnforcedStyle: both
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses
Style/NumericLiterals:
  MinDigits: 5
  Strict: false
Style/RedundantReturn:
  Enabled: true
Style/Semicolon:
  Enabled: true
Style/SingleLineMethods:
  Enabled: true
Style/StabbyLambdaParentheses:
  EnforcedStyle: require_parentheses
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Lint/SafeNavigationChain:
  Enabled: true
Lint/ShadowedArgument:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
